version: '3.4'
services:
  postgres:
    image: postgres:9.6-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
  articles:
    build: ./articles
    environment:
      - PORT=8080
    ports:
      - '8080:8080'
  rating:
    build: ./rating
    environment:
      - PORT=8081
    ports:
      - '8081:8081'