kumuluzee:
  datasources:
    - jndi-name: jdbc/gpu-store-db
      connection-url: jdbc:postgresql://gpu-store_postgres_1:5432/postgres
      username: postgres
      password: postgres
      pool:
        max-size: 20