kumuluzee:
  datasources:
    - jndi-name: jdbc/gpu-store-db
      connection-url: jdbc:postgresql://localhost:5432/postgres
      username: postgres
      password: postgres
      pool:
        max-size: 20